/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: operations["listUsers"];
        put?: never;
        /** Register a user */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate a pending user */
        post: operations["activateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pipeline runs */
        get: operations["listRuns"];
        put?: never;
        /** Create and start a pipeline run */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk-delete old terminal runs
         * @description Deletes runs older than `older_than_days` with one of the given
         *     terminal statuses. Used by ops to keep the table bounded.
         */
        post: operations["cleanupRuns"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get full run timeline */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events stream of run state changes
         * @description Emits `data: <RunView JSON>` events every time the run's status,
         *     step statuses, panels_completed counters, or asset list changes.
         *     Terminates when the run reaches a terminal state.
         */
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-run from the failed/cancelled run's template + prompt */
        post: operations["retryRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a queued or running run */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/formats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available visual+composition format presets. */
        get: operations["listFormats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects */
        get: operations["listProjects"];
        put?: never;
        /** Create a project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a project detail (incl. characters/environments/plot) */
        get: operations["getProject"];
        /** Update project name/description/archived */
        put: operations["updateProject"];
        post?: never;
        /** Delete a project (cascades characters/environments/plot) */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a character in this project */
        post: operations["createCharacter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a character */
        put: operations["updateCharacter"];
        post?: never;
        /** Delete a character */
        delete: operations["deleteCharacter"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an environment in this project */
        post: operations["createEnvironment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update an environment */
        put: operations["updateEnvironment"];
        post?: never;
        /** Delete an environment */
        delete: operations["deleteEnvironment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/social-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a social account in this project */
        post: operations["createSocialAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/social-accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a social account */
        put: operations["updateSocialAccount"];
        post?: never;
        /** Delete a social account */
        delete: operations["deleteSocialAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/plot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Create or update the project's plot */
        put: operations["upsertPlot"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/steps/{idx}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a new attempt for one step inside a run
         * @description Bumps the step's version, marks downstream steps stale, and emits the
         *     matching *.requested event. Allowed on running, awaiting_action,
         *     completed, and failed runs (cancelled is rejected).
         */
        post: operations["regenerateStep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/assemble": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger or re-trigger the assemble step
         * @description Used when auto_assemble=false to manually run the assemble step from an
         *     awaiting_action run, or to re-render with new timeline params from a
         *     completed/failed run.
         */
        post: operations["requestAssemble"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pipeline templates */
        get: operations["listTemplates"];
        put?: never;
        /** Create a template */
        post: operations["createTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a template */
        get: operations["getTemplate"];
        /** Update a template */
        put: operations["updateTemplate"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard aggregates */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live balances for the configured provider API keys */
        get: operations["getBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{id}/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a presigned download URL for an asset */
        get: operations["getAssetUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        IDResponse: {
            id: string;
        };
        RegisterUserRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        UserView: {
            id: string;
            email: string;
            status: string;
            /** Format: date-time */
            created_at: string;
        };
        FormatView: {
            id: string;
            name: string;
            description?: string;
            scope: string;
            script_system_suffix?: string;
            image_prompt_prefix?: string;
            image_prompt_suffix?: string;
            image_model?: string;
            style_reference?: string;
            fps?: number;
            width?: number;
            height?: number;
            codec?: string;
            panel_duration_ms?: number;
            transition?: string;
        };
        CreateRunRequest: {
            prompt: string;
            template_id: string;
            /** @description Format preset id (e.g. "manga", "webtoon"). Overrides project default format. */
            format_id?: string;
            /** @description Optional. Attaches run to a project; characters/environments below select which ones influence this run. */
            project_id?: string;
            /** @description Subset of the project's characters to apply. */
            character_ids?: string[];
            /** @description Subset of the project's environments to apply. */
            environment_ids?: string[];
            /** @description Include the project's plot premise+beats in script payload. */
            use_plot?: boolean;
            overrides?: components["schemas"]["RunOverrides"];
        };
        /**
         * @description Per-run tweaks applied on top of the chosen template. All fields are
         *     optional. `steps` replaces the whole snapshot when present; the other
         *     fields are convenience tweaks merged into the template's steps.
         */
        RunOverrides: {
            /** @description Number of panels (overrides script step's params.panel_count). */
            panel_count?: number;
            /** @description Total final video length, distributed across panels. */
            target_duration_ms?: number;
            /** @description Insert an audio step between image and assemble. */
            enable_audio?: boolean;
            /** @description Override script step's system_prompt. */
            system_prompt?: string;
            /** @description Override script step's model. */
            script_model?: string;
            /** @description Override image step's model. */
            image_model?: string;
            /**
             * @description Image-step style consistency mode. none = parallel (current default);
             *     anchor = panel 0 referenced by all later panels; previous = cumulative
             *     (panel N references 0..N-1). Sequential modes require a ref-capable model.
             * @enum {string}
             */
            style_reference?: "none" | "anchor" | "previous";
            /**
             * @description When false the run pauses in awaiting_action state before the
             *     assemble step instead of auto-rendering. The user then calls
             *     POST /api/runs/{id}/assemble to render. Default true.
             */
            auto_assemble?: boolean;
            /** @description Audio step overrides (voice + model + speed). Applied when enable_audio=true. */
            audio?: {
                voice_id?: string;
                model?: string;
                /** Format: double */
                speed?: number;
            };
            /** @description Auto-upload settings. Enables caption+upload steps after assemble. */
            upload?: {
                enabled?: boolean;
                /** @description youtube_selenium | twitter_selenium */
                provider?: string;
                social_account_ids?: string[];
                /**
                 * Format: date-time
                 * @description RFC3339; if in the future, worker waits.
                 */
                scheduled_at?: string;
                caption_model?: string;
                /** @description Skip LLM, use this caption for all platforms. */
                caption_override?: string;
                platforms?: string[];
            };
            /** @description Assemble step overrides (fps + resolution + codec). */
            assemble?: {
                fps?: number;
                width?: number;
                height?: number;
                /** @enum {string} */
                codec?: "h264" | "h265";
            };
            /** @description Full step override (replaces template snapshot when non-empty). */
            steps?: components["schemas"]["StepConfig"][];
        };
        /** @description Optional params override merged into the step's snapshot params. */
        RegenerateStepRequest: {
            params?: {
                [key: string]: unknown;
            };
        };
        RegenerateStepResponse: {
            run_id: string;
            step_index: number;
            new_attempt_id?: string;
            new_version: number;
        };
        /** @description Optional params override (fps, panel_duration_ms, transition, timeline). */
        RequestAssembleRequest: {
            params?: {
                [key: string]: unknown;
            };
        };
        RequestAssembleResponse: {
            run_id: string;
            step_index: number;
        };
        StepConfig: {
            /** @enum {string} */
            type: "script" | "image" | "audio" | "music" | "assemble" | "upload";
            system_prompt?: string;
            model?: string;
            provider?: string;
            params?: {
                [key: string]: unknown;
            };
        };
        TemplateBody: {
            name: string;
            steps: components["schemas"]["StepConfig"][];
            /**
             * Format: double
             * @description Maximum spend allowed per run from this template. 0 = unlimited.
             * @default 0
             */
            max_cost_usd: number;
        };
        TemplateView: {
            id: string;
            name: string;
            /** @description jsonb step list */
            steps: components["schemas"]["StepConfig"][];
            /**
             * Format: double
             * @description 0 means unlimited.
             */
            max_cost_usd: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RunSummary: {
            id: string;
            template_id: string;
            prompt: string;
            status: string;
            /** Format: double */
            total_cost_usd: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            finished_at?: string | null;
            /** @description ID of the final assembled video asset, if one was produced. */
            video_asset_id?: string;
        };
        StepView: {
            id: string;
            index: number;
            type: string;
            status: string;
            /** @description 1-based attempt counter — bumped on each regenerate. */
            current_version: number;
            /** @description True when an upstream attempt advanced past the version this step's active attempt consumed. */
            is_stale: boolean;
            active_attempt_id?: string;
            input?: {
                [key: string]: unknown;
            } | null;
            /** @description jsonb array (semantics depend on step type) */
            outputs?: unknown;
            provider?: string;
            model?: string;
            /** Format: double */
            cost_usd: number;
            panels_expected: number;
            panels_completed: number;
            error?: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            /** @description Full version history of this step. attempts[len-1] = newest. */
            attempts: components["schemas"]["AttemptView"][];
        };
        AttemptView: {
            id: string;
            step_id: string;
            attempt_no: number;
            status: string;
            input?: {
                [key: string]: unknown;
            } | null;
            /** @description jsonb array */
            outputs?: unknown;
            params_override?: {
                [key: string]: unknown;
            } | null;
            /**
             * @description Map of upstream step_index -> version this attempt consumed.
             *     Lets the UI explain why a step is stale.
             */
            upstream_versions?: {
                [key: string]: number;
            } | null;
            provider?: string;
            model?: string;
            /** Format: double */
            cost_usd: number;
            panels_expected: number;
            panels_completed: number;
            error?: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        AssetView: {
            id: string;
            step_id?: string;
            attempt_id?: string;
            kind: string;
            bucket: string;
            object_key: string;
            mime: string;
            /** Format: int64 */
            bytes: number;
            /** Format: date-time */
            created_at: string;
        };
        CostEntryView: {
            id: string;
            step_id?: string;
            attempt_id?: string;
            provider: string;
            model?: string;
            /** Format: double */
            units?: number;
            unit_label?: string;
            /** Format: double */
            unit_cost_usd?: number;
            /** Format: double */
            total_cost_usd: number;
            /** Format: date-time */
            occurred_at: string;
        };
        RunView: {
            id: string;
            template_id?: string;
            prompt: string;
            /** @description queued | running | awaiting_action | completed | failed | cancelled */
            status: string;
            current_step_index: number;
            expected_steps: number;
            auto_assemble: boolean;
            /** Format: double */
            total_cost_usd: number;
            /**
             * Format: double
             * @description 0 means unlimited.
             */
            max_cost_usd: number;
            error?: string;
            config_snapshot?: components["schemas"]["StepConfig"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            steps: components["schemas"]["StepView"][];
            assets?: components["schemas"]["AssetView"][];
            cost_entries?: components["schemas"]["CostEntryView"][];
        };
        CleanupRunsRequest: {
            /** @description Delete runs whose created_at is more than N days old. */
            older_than_days: number;
            /** @description Only delete runs in these terminal statuses. Default = [completed, failed, cancelled]. */
            statuses?: string[];
        };
        CleanupRunsResponse: {
            deleted: number;
        };
        Provider: {
            name: string;
            currency: string;
            /** Format: double */
            used: number;
            /** Format: double */
            limit: number;
            /** Format: double */
            remaining: number;
            unit_label: string;
            /** Format: int64 */
            reset_unix?: number;
            error?: string;
        };
        BalancesView: {
            providers: components["schemas"]["Provider"][];
        };
        PresignedAssetURL: {
            /** Format: uri */
            url: string;
            mime: string;
        };
        ProviderCost: {
            provider: string;
            /** Format: double */
            total_cost_usd: number;
        };
        DayCost: {
            /** Format: date */
            date: string;
            /** Format: double */
            total_cost_usd: number;
        };
        StatsView: {
            runs_by_status: {
                [key: string]: number;
            };
            /** Format: double */
            total_cost_usd: number;
            cost_by_provider: components["schemas"]["ProviderCost"][];
            cost_by_day: components["schemas"]["DayCost"][];
        };
        ProjectBody: {
            name: string;
            description?: string;
            /** @description Default Studio overrides hydrated when this project is picked. */
            defaults?: {
                [key: string]: unknown;
            };
            archived?: boolean;
        };
        ProjectView: {
            id: string;
            name: string;
            description: string;
            defaults: {
                [key: string]: unknown;
            };
            archived: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CharacterBody: {
            name: string;
            description?: string;
            traits?: {
                [key: string]: unknown;
            };
            ref_asset_ids?: string[];
        };
        CharacterView: {
            id: string;
            project_id: string;
            name: string;
            description: string;
            traits: {
                [key: string]: unknown;
            };
            ref_asset_ids: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        EnvironmentBody: {
            name: string;
            description?: string;
            traits?: {
                [key: string]: unknown;
            };
            ref_asset_ids?: string[];
        };
        EnvironmentView: {
            id: string;
            project_id: string;
            name: string;
            description: string;
            traits: {
                [key: string]: unknown;
            };
            ref_asset_ids: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        SocialAccountBody: {
            /** @description youtube_selenium | twitter_selenium | ... */
            platform: string;
            label?: string;
            firefox_profile_path?: string;
            extra?: {
                [key: string]: unknown;
            };
        };
        SocialAccountView: {
            id: string;
            project_id: string;
            platform: string;
            label: string;
            firefox_profile_path: string;
            extra: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PlotBeatView: {
            name: string;
            description: string;
            order: number;
        };
        PlotView: {
            id: string;
            project_id: string;
            name: string;
            premise: string;
            beats: components["schemas"]["PlotBeatView"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PlotBody: {
            name?: string;
            premise?: string;
            beats?: components["schemas"]["PlotBeatView"][];
        };
        ProjectDetailView: {
            project: components["schemas"]["ProjectView"];
            characters: components["schemas"]["CharacterView"][];
            environments: components["schemas"]["EnvironmentView"][];
            social_accounts: components["schemas"]["SocialAccountView"][];
            plot?: components["schemas"]["PlotView"] | null;
        };
    };
    responses: {
        /** @description error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        PathID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listUsers: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterUserRequest"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IDResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    activateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listRuns: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Comma-separated status filter (e.g. "running,completed"). */
                status?: string;
                /** @description Case-insensitive substring match on the prompt. */
                q?: string;
                /** @description Filter by project. Omit to include runs without a project too. */
                project_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IDResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    cleanupRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CleanupRunsRequest"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanupRunsResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    streamRunEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    retryRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IDResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listFormats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormatView"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectView"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectBody"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IDResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectBody"];
            };
        };
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    createCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterBody"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IDResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterBody"];
            };
        };
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    deleteCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    createEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnvironmentBody"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IDResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnvironmentBody"];
            };
        };
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    deleteEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    createSocialAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SocialAccountBody"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IDResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateSocialAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SocialAccountBody"];
            };
        };
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    deleteSocialAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    upsertPlot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlotBody"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IDResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    regenerateStep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
                idx: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RegenerateStepRequest"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegenerateStepResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    requestAssemble: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RequestAssembleRequest"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestAssembleResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateView"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateBody"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IDResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateBody"];
            };
        };
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getBalances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalancesView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAssetUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignedAssetURL"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
